queries = {
    "get_user_from_uuid": """SELECT * FROM users WHERE uuid = ?""",
    "get_user_id_from_uuid": """SELECT (id) FROM users WHERE uuid = ?""",
    "get_game_state": """SELECT * FROM game_state where game = (SELECT id FROM game WHERE uuid = ?)""",
    "get_games": """SELECT * FROM game""",
    "get_game_from_id": """SELECT * FROM game WHERE id = ?""",
    "get_game_from_uuid": """SELECT * FROM game WHERE uuid = ?""",
    "get_user_id_from_uuid": """SELECT id FROM users WHERE uuid = ?""",
    "get_is_game_full": """SELECT (white, black) FROM game WHERE id = ?""",
    "post_signup": """INSERT INTO users (username, hashed_password, uuid) VALUES (?, ?, ?)""",
    "post_login": """SELECT hashed_password, uuid FROM users WHERE username = ? LIMIT 1""",
    "post_game_state": """INSERT INTO game_state (activePlayer, gameState, game) VALUES (?, ?, ?)""",
    "post_create_game": """INSERT INTO game (white, uuid) VALUES (?, ?)""",
    "insert_starting_game_state": """INSERT INTO game_state (activePlayer, gameState, game) VALUES (?, ?, ?)""",
}
